### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rooney** [rooney/OpenClinica#2]
# Cosmetic changes
- [ ] side arrow images missing in bridge side info bar.  up arrows are working fine (ex: next to Alerts & Messages.

 ## General/Global Comments 
- [ ] The Test environment should have a marking (supplied by Caitlin) making it clear that it is not the Prod environment so people don't use it by accident. Check with Caitlin - she made a button or changed the font or SOMETHING:
![image](https://user-images.githubusercontent.com/8669485/29752415-768e9660-8b2b-11e7-862f-e39fa89e26d6.png)
- [ ] Button in the header indicating environment should have drop-down to toggle to a different environment for that study (Test or Production).
- [ ] Mark-up level edit - see if there is a way to get our tables to look sharper. (Ben?)
- [ ] Change Study/Site: Text looks squished. Also, If a study hasn’t been published to production insert the text “not yet published” where the red circle is. The text can be red too.
![image](https://user-images.githubusercontent.com/8669485/29742240-509df8de-8a49-11e7-8c40-b446a1af7539.png)

### Subject Matrix:
- [ ] Subject Matrix > view a subject: CRFs are listed in the order they were added to the event in sbs, 
![image](https://user-images.githubusercontent.com/8669485/29715184-307d6d9e-8974-11e7-829e-e8c792c9be13.png)
but if I view by event, CRFs are listed in reverse order:
![image](https://user-images.githubusercontent.com/8669485/29715131-0a22a33a-8974-11e7-9ce4-775ce1c92572.png)

- [ ] Subject Matrix - action icon for reassign - Caitlin submitted an icon update:
I made a new icon for this called "icon-reassign3" - will be in a new font file in the next commit
This icon should also be replaced in the following screens:
Subject Matrix > View a subject > Reassign CRF to new version AND
Tasks>CRFs>Batch CRF version migration
- [ ] This has been an issue for a long time, but thought I'd mention it...Subject Matrix > View a subject > CRFs are listed in order 1,2,3,4. Enter data into CRF 1. It returns you to the View subject record, but now the CRFs are listed in order 2,3,4,1. This has been a point of confusion for site users in 3.x for some time- if we can take it out, let's!

# Ready For Review
- [x] When the tasks mega menu is open it is not closing in the right wait we can demo it to show you.
- [x] [Cosmetic] Update the favicon to use the OC swoosh logo from openclinica.com. This should be carried over to the study manager/designer apps as well.
- [x] Subject Matrix > View Subject: It looks like the random ; is there when no DE has been done yet. It should just be blank, but the column should be a standard width so the set of icons line up no matter what is in that column:
![image](https://user-images.githubusercontent.com/8669485/29751856-636c1378-8b21-11e7-8b7b-e1b18acfbb4d.png)
- [x] Subject Matrix>click a scheduled event>view/enter data (Enter or Validate Data for CRFs in EventName). Top section with Event details should not have a row for Location.
- [x] Subject Matrix >  Schedule Event (also in View by Event > Schedule Event)
0 is auto-populated in minutes field after clicking "Proceed to enter data"- should be blank so user can easily move on to DE. Even if a valid time (e.g. 11:11 is entered, the minutes are reset to 0 and the same message displays. Can't get to the DE screen): Also - flags are displayed rather than bubbles.
![image](https://user-images.githubusercontent.com/8669485/29714671-262a7fe6-8972-11e7-995d-eed9ff7887ae.png)
- [x] Subject Matrix > View a subject > migrate a CRF to a new version > select the new version and continue - table looks odd: it has vertical divider lines, but not horizontal divider lines:
![image](https://user-images.githubusercontent.com/8669485/29753073-d0c71ce0-8b37-11e7-8f25-a83b65a13f6f.png)
- [x] Still layered, just not as much (see below). Also, fields are squished now - not as much space between each field, and has old add and cancel buttons:
![image](https://user-images.githubusercontent.com/8669485/30297965-b01452ba-9717-11e7-9c80-83a544dcdaf9.png)
- [x] Subject Matrix - Add New Subject - type info in, use the Tab key to maneuver to the "add" button (has a border around it to show it has "focus") and press enter. Doesn't add the subject and kicks you out to the home screen. Enter key should work on any button that has focus.
- [x] Subject Matrix > Click a scheduled Event icon > enter/edit data:
Location should be removed
Status for Initial data entry should be DE Started (orange box/pencil)
Title Initial Data Entry should be Data Entry (or should it be "Last Modified by:"?)
Scroll bar should be removed
![image](https://user-images.githubusercontent.com/8669485/29750284-f17ddde8-8b0a-11e7-86ef-0f435a8e26f7.png)
Side bar for that same window - replace initial data entry icon with DE Started icon
![image](https://user-images.githubusercontent.com/8669485/29742146-c330126c-8a47-11e7-9c2a-cedd6620663d.png)
- [x] The hover text for Data Entry Started still says Initial Data Entry:
![image](https://user-images.githubusercontent.com/8669485/29752075-2672bd42-8b25-11e7-8afd-aa3a00c528e9.png) (in View by Event also)
- [x] Remove Locations column, make Actions header Event Actions, remove the random ; in CRF section:
![image](https://user-images.githubusercontent.com/8669485/29692178-bd780bdc-88fc-11e7-8492-da8a69b08085.png)
- [x] Left banner text is messy: Different fonts and different indentation ~~ and for some reason "scheduled" is a hyperlink (that doesn't go anywhere) ~~ The hyperlinks I see open a specific occurrence of the event
![image](https://user-images.githubusercontent.com/8669485/29742030-b0524f7c-8a45-11e7-9f27-497184a6b8ce.png)
- [x] Subject Matrix - view a subject, then click Schedule New Event and Cancel - throws you back to the Subject Matrix; should put you back on the View Subject screen.
- [x] Subject Matrix - view subject, edit event: Event-query icons look like they have a status of "closed" even when there's no query 
![image](https://user-images.githubusercontent.com/8669485/29742277-0b5a54f6-8a4a-11e7-91f4-a50ad2888b5f.png)
- [x] Sidebar doesn't populate PI or IRB approval date - did we get rid of those in sbs? If so, they should be removed here. If not, why aren't they populating?
![image](https://user-images.githubusercontent.com/8669485/29742074-6cdb7902-8a46-11e7-82c9-c5a3625b8720.png)
- [x] Subject Matrix > Add New Subject - border is layered:
![image](https://user-images.githubusercontent.com/8669485/29742093-cc88d836-8a46-11e7-9832-ec7b9a0fbe46.png)
- [x] Subject Matrix > Add New Subject AND Tasks> Add Subject should display same screen, which should appear as follows (only better aligned):
![image](https://user-images.githubusercontent.com/8669485/29742097-01c49ed6-8a47-11e7-8678-7fd4f590d9c3.png)
- [x] Subject Matrix - hover over each status icon. There should be a space between the : and the status - fixed on some statuses, not fixed on others:
![image](https://user-images.githubusercontent.com/8669485/29741968-b77239b2-8a44-11e7-8c47-8e59f6c8788f.png)
similarly...
- [x] Subject Matrix > click on a non-repeating event icon and a repeating event icon - Status text is inconsistent; repeating event has the text bold and has an extra space before the colon; non-repeating event needs a space after the colon.
![image](https://user-images.githubusercontent.com/8669485/29751763-01739b74-8b20-11e7-868a-8e4804347eea.png)
- [x] Subject Matrix>View a subject>Subject Record link>Edit - flag should be query bubble:
![image](https://user-images.githubusercontent.com/8669485/29742110-2ff76b80-8a47-11e7-9415-6dc5b2e6dd30.png)
- [x] Subject Matrix>click a scheduled event>view/enter data. Side bar should not have location, and form icons should be aligned:
![image](https://user-images.githubusercontent.com/8669485/29742124-6a711e00-8a47-11e7-9b87-371f0de1d71f.png)
- [x] Subject Matrix > View by Event has same icon for unscheduled event and CRF not started - may need new icon from Caitlin?
![image](https://user-images.githubusercontent.com/8669485/29742511-981024bc-8a4e-11e7-8c32-0ccf21afeeae.png)
- [x] Subject Matrix > View a subject > click Global Subject Record link, then Edit Record - Flag should be replaced with empty query bubble:
![image](https://user-images.githubusercontent.com/8669485/29750452-ce2091b2-8b0d-11e7-86a1-e7ffa37b5ea0.png)
When I cancel out of the Edit screen, it returns me to Administer Subjects. Should return to View Subject Record screen (where I was prior to clicking Global Subject Record/Edit)
- [x] Tasks >Schedule Event - Flags should be empty query bubbles. Also, for start date/time, the asterisk should be next to the start date field (time is not required, but start date is.)
![image](https://user-images.githubusercontent.com/8669485/29741639-1ee6c316-8a3f-11e7-8769-3dcd05cc9ad6.png)

- [x] After creating a study subject clear all data in the inputs. 
- [x] [Cosmetic ] Implement new skin -> https://github.com/OpenClinica/openclinica-ux/tree/oc2017-bridge-8-23-17
- [x] [Cosmetic ] Put this CSS in https://github.com/openclinica/openclinica-ux/tree/oc2017-bridge-8-1-17
- [x] oc logo is still broken on the link referenced (demo), but looks fine on dev. (I'm assuming the updates weren't pushed to demo.)
- [x] ~~Remove the User Audit log link from the Tasks> Monitor & Manage data~~
~~- [Cosmetic]Maybe I’m a spazzy mouser, but I find that often (almost always) when I’m headed to the Tasks menu the user menu often pops down as I "drive by".~~
- [x] ~~View by event has "initial data entry" icon for event status - should be "Data Entry Started" icon, and icon key should be displayed in the left (like it is in view by subject):
![image](https://user-images.githubusercontent.com/8669485/29742229-1c43b524-8a49-11e7-97cb-e3504c10daac.png)~~
- [x] ~~There's too much space between buttons on Subject Matrix > View subject screen:
![image](https://user-images.githubusercontent.com/8669485/29637185-5ffaf996-8821-11e7-9edd-4050c9a5cf87.png)~~
- [x] ~~ Alerts and Messages still says "first last" rather than the actual first name and last name of the user logged in:
![image](https://user-images.githubusercontent.com/8669485/29750077-953009f6-8b07-11e7-9e90-68a6e34ecea5.png)~~ Moved to Functional list
- [x] See:
 https://docs.google.com/spreadsheets/d/1KN_vTvIj7EwuPji6A9dNe999RfiWEyU45mlRwicLAl4/edit#gid=0
- [x] Need spacing like this on all pages of runtime.
![image](https://user-images.githubusercontent.com/8669485/29668242-718fb2f0-88ad-11e7-9a55-cd2e29aa3566.png)
- [x] Click on the study name top left corrner > View an Event > View a form in the event - Metadata icon is incorrect (it shows the edit icon)
![image](https://user-images.githubusercontent.com/8669485/29742198-9f98b038-8a48-11e7-811e-977765ca894a.png)
- [x] [Functional & Cosmetic] Tasks menu should be updated to remove unused options. It should only have these sections/options: ~~GROUPS should come off the menu.~~
![image](https://user-images.githubusercontent.com/8669485/29742206-c34e0ed8-8a48-11e7-9b92-64bddab4c285.png)
 - [x] Balance 'Task' menu so items aren't overly stacked on either left or right
![image](https://user-images.githubusercontent.com/8669485/29742605-70a59f40-8a50-11e7-81a7-c746bb4cc191.png)

### - Create Dataset:

- [x] Tasks>Create Dataset>start to build a dataset...font sizes in selection area are inconsistent: 
![image](https://user-images.githubusercontent.com/8669485/29741434-f09ba39a-8a3a-11e7-936a-fad228a67ec1.png)
(though I went in later, and they were consistent - I guess they're inconsistently inconsistent)
![image](https://user-images.githubusercontent.com/8669485/29741858-dd90f20c-8a42-11e7-86c4-7f146a1f5c93.png)

- [x] Tasks>Create Dataset>start to build a dataset...select some items>in left selection bar, select View Selected Items.
Group attributes should be removed
Interviewer fields should be removed
Event Location should be removed
![image](https://user-images.githubusercontent.com/8669485/29741475-9516b7e8-8a3b-11e7-8962-bf801dc02048.png)

- [x] Tasks>Create Dataset...get to the end - alignment of selections and radio buttons is messy:
![image](https://user-images.githubusercontent.com/8669485/29742254-8a91e92e-8a49-11e7-90a8-0f71006e9087.png)

- [x] Tasks>Create Dataset...workflow should be removed (from all screens)
Also...there are scroll bars on many screens that are not needed  and should be removed.
![image](https://user-images.githubusercontent.com/8669485/29741525-f77d4ba8-8
![image](https://user-images.githubusercontent.com/8669485/29741614-bd2fec4c-8a3e-11e7-94a8-4f5b344b76c9.png)
a3c-11e7-9b77-38d5584d41e9.png)

- [x] Tasks>Create Dataset - create a dataset, click Go back to dataset - old delete icon should be replaced with new one:
![image](https://user-images.githubusercontent.com/8669485/29741905-accbdee2-8a43-11e7-950d-b980876d3ed9.png)

## Tasks>Sites

- [x] Tasks>Sites>Edit a site>Expand one of the events:
Remove Double Data Entry and Password Required
Not sure if SDV status should stay or go (since this can't be set at the study level)
![image](https://user-images.githubusercontent.com/8669485/29753832-b9d9d454-8b47-11e7-992e-e9ff59a7611a.png)

- [x] All links to "Go back to build study page" should be removed:
![image](https://user-images.githubusercontent.com/8669485/30034858-40cc070e-9172-11e7-914a-eddf9932356c.png)

# Done
